from pathlib import Path

import importlib.util


ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "render_daily_hot_issues_pdf.py"


spec = importlib.util.spec_from_file_location("render_daily_hot_issues_pdf", SCRIPT)
renderer = importlib.util.module_from_spec(spec)
assert spec.loader is not None
spec.loader.exec_module(renderer)


def test_strip_yaml_frontmatter_before_pdf_html_rendering():
    md = """---
title: 테스트
created: 2026-04-26
---

# 본문 제목

- 항목
"""
    html = renderer.markdown_to_html(md)
    assert "title: 테스트" not in html
    assert "created: 2026-04-26" not in html
    assert "항목" in html


def test_render_document_uses_report_masthead_and_newspaper_layout():
    md = """---
title: 테스트
---

# 오늘의 핫이슈 리포트 — 2026-04-26

- 기준 창: 오늘
- 해석 원칙: 원문 중심

## Executive Summary

중요한 원문 내용입니다.

### 1. OpenAI API 제공

- 원문 내용: API가 제공된다.
- 왜 중요한가: 도구 호출 검증이 필요하다.
"""
    doc = renderer.render_document(md, "2026-04-26 21:00 KST")
    assert "report-cover" in doc
    assert "body-grid" in doc
    assert "TODAY'S HOT ISSUES" in doc
    assert "오늘의 핫이슈 리포트" in doc
    assert "column-count: 1" in doc
    assert "issue-card" in doc
    assert "data-no=\"01\"" in doc
    assert "title: 테스트" not in doc


def test_render_document_uses_compact_cover_and_reader_first_layout():
    md = """# 오늘의 핫이슈 리포트 — 2026-04-27

- 보고 기준 시각: 2026-04-27 20:00 KST

## 한눈에 보기
오늘은 공식 발표와 보도를 출처 성격별로 분리한다.

## 오늘의 체크리스트
- 오늘 확인: 공식 원문을 확인한다.

## 주요 이슈
### OpenAI, SWE-bench Pro 공개
- 출처 성격: 공식 블로그.
- 확인된 사실: 새 벤치마크가 공개됐다.
- 왜 중요한가: 평가 설계에 영향이 있다.
- 오늘 할 일: 원문을 확인한다.
- 근거: [OpenAI blog](https://openai.com/news/), 2026-04-27 확인.
- 불확실성: 재현 결과는 미확인이다.
"""
    doc = renderer.render_document(md, "2026-04-27 20:59 KST")
    assert "보고 기준 · 2026-04-27 20:00 KST" in doc
    assert "보고 기준 · 2026-04-27 20:59 KST" not in doc
    assert "reader-first-cover" in doc
    assert "display: grid" not in doc.split(".cover-cards", 1)[1].split("}", 1)[0]
    assert "Generated by Jinwang Jarvis" not in doc
    assert "보고 기준" in doc
    assert "독자형 출처 라벨" in doc


def test_render_document_strips_existing_markdown_issue_numbers():
    md = """# 오늘의 핫이슈 리포트 — 2026-04-27

## 주요 이슈
### 1. OpenAI, 새 벤치마크 공개
- 출처 성격: 공식 블로그.

### 02) 한국 AI 반도체 보도 확산
- 출처 성격: 보도.
"""
    doc = renderer.render_document(md, "2026-04-27 20:59 KST")
    assert 'data-no="01"' in doc
    assert 'data-no="02"' in doc
    assert ">OpenAI, 새 벤치마크 공개<" in doc
    assert ">한국 AI 반도체 보도 확산<" in doc
    assert ">1. OpenAI" not in doc
    assert ">02) 한국" not in doc


def test_render_document_excludes_internal_appendix_and_local_paths():
    md = """# 오늘의 핫이슈 리포트 — 2026-04-26

## 주요 이슈

### 공식 발표
- 확인된 사실: 공개 발표가 있었다.
- 왜 중요한가: 후속 확인이 필요하다.
- 오늘 할 일: 공식 원문을 확인한다.

## 부록: 내부 생성 근거
- source: /home/jinwang/workspace/jinwang-jarvis/data/internal.json
- source audit: internal
"""
    doc = renderer.render_document(md, "2026-04-26 21:00 KST")
    assert "부록: 내부 생성 근거" not in doc
    assert "/home/jinwang" not in doc
    assert "source audit" not in doc
    assert "독자형 출처 라벨 · 사실/해석 분리" in doc
    assert "SECTION" not in doc
