#!/usr/bin/env python3
"""Render Jinwang Jarvis daily hot-issues markdown into PDF.

Preferred path: if a TeX engine is present and a .tex file is provided, cron jobs may
compile the TeX directly. This helper provides a robust fallback using WeasyPrint so
Discord can still receive a PDF on OpenBox where TeX is not installed.
"""
from __future__ import annotations

import argparse
import html
import re
from pathlib import Path
from datetime import datetime, timezone, timedelta

KST = timezone(timedelta(hours=9))

CSS = """
@page { size: A4; margin: 18mm; }
body { font-family: 'Noto Sans CJK KR', 'Noto Sans KR', 'DejaVu Sans', sans-serif; color: #111827; line-height: 1.55; }
h1 { color: #1f4e79; font-size: 28px; margin-bottom: 0.15em; }
h2 { color: #1f4e79; border-bottom: 1px solid #cbd5e1; padding-bottom: 0.15em; margin-top: 1.2em; }
h3 { color: #374151; margin-top: 0.9em; }
a { color: #1f4e79; }
.header { background: #eef4fa; border-left: 5px solid #1f4e79; padding: 10px 14px; margin: 12px 0 18px; }
.meta { color: #6b7280; font-size: 12px; }
code { background: #f3f4f6; padding: 1px 4px; border-radius: 3px; }
ul { padding-left: 1.3em; }
hr { border: none; border-top: 1px solid #e5e7eb; }
"""

def md_inline(text: str) -> str:
    text = html.escape(text)
    text = re.sub(r"`([^`]+)`", r"<code>\1</code>", text)
    text = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"\[([^\]]+)\]\((https?://[^)]+)\)", r'<a href="\2">\1</a>', text)
    return text

def strip_yaml_frontmatter(md: str) -> str:
    """Remove YAML frontmatter before rendering human-facing PDF pages."""
    if md.startswith("---\n"):
        end = md.find("\n---\n", 4)
        if end != -1:
            return md[end + len("\n---\n"):].lstrip()
    return md


def markdown_to_html(md: str) -> str:
    md = strip_yaml_frontmatter(md)
    out = []
    in_ul = False
    for raw in md.splitlines():
        line = raw.rstrip()
        if not line:
            if in_ul:
                out.append("</ul>"); in_ul = False
            continue
        if line.startswith("# "):
            if in_ul: out.append("</ul>"); in_ul = False
            out.append(f"<h1>{md_inline(line[2:])}</h1>")
        elif line.startswith("## "):
            if in_ul: out.append("</ul>"); in_ul = False
            out.append(f"<h2>{md_inline(line[3:])}</h2>")
        elif line.startswith("### "):
            if in_ul: out.append("</ul>"); in_ul = False
            out.append(f"<h3>{md_inline(line[4:])}</h3>")
        elif line.startswith("- "):
            if not in_ul:
                out.append("<ul>"); in_ul = True
            out.append(f"<li>{md_inline(line[2:])}</li>")
        else:
            if in_ul:
                out.append("</ul>"); in_ul = False
            out.append(f"<p>{md_inline(line)}</p>")
    if in_ul:
        out.append("</ul>")
    return "\n".join(out)

def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("markdown", type=Path)
    ap.add_argument("--pdf", type=Path, required=True)
    ap.add_argument("--html", type=Path)
    args = ap.parse_args()
    md = args.markdown.read_text(encoding="utf-8")
    now = datetime.now(KST).strftime("%Y-%m-%d %H:%M KST")
    body = markdown_to_html(md)
    doc = f"""<!doctype html><html><head><meta charset='utf-8'><style>{CSS}</style></head><body>
<div class='meta'>Generated by Jinwang Jarvis · {html.escape(now)}</div>
{body}
</body></html>"""
    html_path = args.html or args.pdf.with_suffix(".html")
    html_path.parent.mkdir(parents=True, exist_ok=True)
    args.pdf.parent.mkdir(parents=True, exist_ok=True)
    html_path.write_text(doc, encoding="utf-8")
    from weasyprint import HTML
    HTML(filename=str(html_path)).write_pdf(str(args.pdf))
    print(args.pdf)
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
